module.exports = [
  { id: 1, document: 'cni', project_id: 1, mortgagor_id: 1, status: 'refusé', mois: null, year: null },
  { id: 2, document: 'cni', project_id: 1, mortgagor_id: 2, status: 'validé', mois: null, year: null },
  { id: 3, document: 'cni', project_id: 1, mortgagor_id: 1, status: 'validé', mois: null, year: null },
  { id: 4, document: 'cni', project_id: 2, mortgagor_id: 3, status: 'validé', mois: null, year: null },
  { id: 5, document: 'livret_famille', project_id: 1, mortgagor_id: null, status: 'validé', mois: null, year: null },
  { id: 6, document: 'bulletins_salaire', project_id: 1, mortgagor_id: 2, status: 'empty', mois: 1, year: 2021 },
  { id: 7, document: 'bulletins_salaire', project_id: 1, mortgagor_id: 2, status: 'validé', mois: 2, year: 2021 },
  { id: 8, document: 'bulletins_salaire', project_id: 1, mortgagor_id: 2, status: 'validé', mois: 3, year: 2021 },
  { id: 9, document: 'avis_impots', project_id: 1, mortgagor_id: null, status: 'validé', mois: null, year: 2020 },
  { id: 10, document: 'avis_impots', project_id: 1, mortgagor_id: null, status: 'validé', mois: null, year: 2019 },
  { id: 11, document: 'avis_impots', project_id: 1, mortgagor_id: null, status: 'validé', mois: null, year: 2018 },
  { id: 12, document: 'avis_impots', project_id: 1, mortgagor_id: null, status: 'validé', mois: null, year: 2017 },
  { id: 13, document: 'avis_impots', project_id: 2, mortgagor_id: 3, status: 'validé', mois: null, year: 2019 },
  { id: 14, document: 'avis_impots', project_id: 2, mortgagor_id: 3, status: 'validé', mois: null, year: 2020 },
  { id: 15, document: 'offre_pret', project_id: 2, mortgagor_id: null, status: 'validé', mois: null, year: null },
  { id: 16, document: 'tableau_amortissement', project_id: 2, mortgagor_id: null, status: 'validé', mois: null, year: null },
  { id: 17, document: 'estimation_bien', project_id: 2, mortgagor_id: null, status: 'validé', mois: null, year: null },
  { id: 18, document: 'avis_impots', project_id: 2, mortgagor_id: 3, status: 'validé', mois: null, year: 2018 }
]